[package]
name = "burt"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.25.0"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

[profile.release.package."*"]
opt-level = 3